const abbreviations = {
    "FX": "Forex",
    "CIB": "Corporate Internet Banking",
    "ASAP": "ASAP",
    "ACT": "account",
    "ACCT": "account",
    "MOB": "mobile",
    "CHQ": "cheque",
    "FD": "Fixed Deposit",
    "TD": "Time Deposit",
    "RD": "recurring Deposit",
    "DD": "Demand draft",
    "PO": "Pay order",
    "FT": "Fund Transfer",
    "CI": "Customer ID",
    "CIF": "Customer Information File",
    "CUST_ID": "Customer ID",
    "TXNID": "transaction ID",
    "MF": "Mutual Fund",
    "DC": "debit Card",
    "CC": "Credit Card",
    "OD": "Overdraft",
    "TL": "Term Loan",
    "PL": "Personal Loan",
    "BL": "Business Loan",
};

module.exports = abbreviations;
